# Generated by Django 5.2.4 on 2025-07-08 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_raised",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 7, 8, 12, 32, 42, 548719, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
