# Generated by Django 5.2.4 on 2025-07-09 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="time_raised",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 9, 40, 13, 282266, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
