# Generated by Django 5.2.4 on 2025-07-09 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0002_alter_customer_time_raised"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="time_raised",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 10, 27, 58, 77928, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
